### ISSUE TITLE
City of Mist

### ISSUE THREAD

**Issue by nazwadi** [Gates-Of-Time/development-tracker#25]
- [ ] Quest validation
- [ ] Mob placement / validation
  - [ ] Spawn locations are correct 
  - [x] Pathings are correct (also check no pathing through buildings/doors/etc)
  - [x] Named mobs are era correct
- [x] Tradeskill container placement / validation
- [x] Wiki documentation
  - [x] General zone info
    - [x] Map
    - [x] Mobs
    - [x] Items
    - [x] Quests
    - [x] Lore
  - [x] Quest detail pages
  - [x] Mob detail pages
  - [x] Item detail pages
- [x] Loot drop validation

**Comment by nazwadi** [comment]
## Items Not Dropping (Running List)

1. <s>Woodman's Staff (not in database)</s> found in db; drops from Neh`Ashiir
2. <s>A Stone Key (not in database)</s> found in db; appears as "Stone Key"
3. <s>[1284 - Ruined Scaled Coif](https://editor.fvproject.com/index.php?editor=loot&action=32&search=1284)</s>found in db;
4. <s>[1285 - Ruined Scaled Visor ](https://editor.fvproject.com/index.php?editor=loot&action=32&search=1285)</s>found in db;
5. <s>[1286 - Ruined Scaled Neckguard ](https://editor.fvproject.com/index.php?editor=loot&action=32&search=1286)</s>found in db;
6. <s>[1287 - Ruined Scaled Coat](https://editor.fvproject.com/index.php?editor=loot&action=32&search=1287)</s>found in db;
7. <s>[1288 - Ruined Scaled Mantle](https://editor.fvproject.com/index.php?editor=loot&action=32&search=1288)</s>found in db;
8. <s>[1289 - Ruined Scale Cape](https://editor.fvproject.com/index.php?editor=loot&action=32&search=1289)</s>found in db;
9. <s>[1290 - Ruined Scaled Skirt](https://editor.fvproject.com/index.php?editor=loot&action=32&search=1290)</s> found in db;
10. [1291 - Ruined Scaled Sleeves ](https://editor.fvproject.com/index.php?editor=loot&action=32&search=1291)(not dropping in CoM)
11. [1292 - Ruined Scaled Bracelet](https://editor.fvproject.com/index.php?editor=loot&action=32&search=1292) (not dropping in CoM)
12. [1293 - Ruined Scaled Gloves](https://editor.fvproject.com/index.php?editor=loot&action=32&search=1293) (not dropping in CoM)
13. [1294 - Ruined Scaled Pants](https://editor.fvproject.com/index.php?editor=loot&action=32&search=1294) (not dropping in CoM)
14. [1295 - Ruined Scaled Boots](https://editor.fvproject.com/index.php?editor=loot&action=32&search=1295) (not dropping in CoM)

**Comment by nazwadi** [comment]
Ornate Rune Shield currently configured to drop from Terror and Dread Wraiths.  Alla's seems to indicate it was moved to those mobs at some point, because there's a post on Dec 16 2000 (https://everquest.allakhazam.com/db/item.html?item=1120) showing it dropped from Neh`Ashiir. P99 (https://wiki.project1999.com/Ornate_Rune_Shield) says that as well. More to follow.  I'll continue to look for additional sources.

**Comment by nazwadi** [comment]
Item detail pages complete.

**Comment by nazwadi** [comment]
## Remaining list of NPC's to review:
None of the following mobs exist on p99.

- <s>**Kilidna**</s> is Omens of War era (Shadowknight Epic 2.0) and should be disabled.
* Can't find any information on <s>**Hyramm Brazenshield**</s>
* <s>**a War Bone Overlord**</s> -  Earliest comment on Allas is Jun 24, 2006 (Prophecy of Ro Era): https://everquest.allakhazam.com/db/npc.html?id=21701#m1151169007281506196
* <s>**a raging golem**</s> - earliest Alla's posts are 2006

* <s>**Tzirathk**</s> - earliest Alla's post is 2002

The following NPC's I _suspect_ were put in after the August 26, 2003 patch on EQ Live that revamped CoM:
* <s>**a Spectral Beguiler**</s> - name changed to "Spectral Beguiler" [on February 15 2017 patch](https://everquest.allakhazam.com/db/npc.html?id=13082#m1487430801168011192); earliest Alla's posts are 2003
* <s>**a Terror Wraith**</s> - later changed to "Terror Wraith"; earliest Alla's posts are 2003
* <s>**Gyrating Green Slime**</s> - earliest Alla's posts are 2004
* <s>**Marl Kastane**</s> - earliest Alla's posts are 2004; for Shadowknight Epic; he was updated in the August 15, 2018 patch.  Also found in Kerra Isle (kerraridge); later in Toxxulia Forest when it was merged with Kerra Isle
* <s>**Plaguebone Warlord**</s> - may be Luclin era; earliest Alla's posts are 2003; drops loot for Claw of the Spiritual Elder (No. 6);
* <s>**Ravenous War Bone Skeleton**</s> - may be Luclin era; earliest Alla's posts are 2003; drops loot for Claw of the Spiritual Elder (No. 6);
* <s>**a corrupt spiritualist**</s> - may be Luclin era (see related quest Claw of the Mature Patriarch (No. 5))
* <s>**a Dread Wraith**</s> - 2003 era Alla's post shows "a Dread Wraith" and "Dread Wraith" [both existed at the same time](https://everquest.allakhazam.com/db/npc.html?id=12986#m106378618955567)
* <s>**Dread Wraith**</s> - 2003 era Alla's post shows "a Dread Wraith" and "Dread Wraith" [both existed at the same time](https://everquest.allakhazam.com/db/npc.html?id=12986#m106378618955567)
* <s>**a Mighty Golem**</s> - name changed to "Mighty Golem" [on Feb 15 2017 patch](https://everquest.allakhazam.com/db/npc.html?id=13080#m148780582594256927); earliest Alla's posts are 2003

**Comment by nazwadi** [comment]
Mob detail pages complete (pending spawn decisions for NPC list above).  Wiki documentation complete.

**Comment by nazwadi** [comment]
#TODO: Confirm whether or not Shaman epic quest pages were already dropping in CoM and EJ on Kunark release.

* 18451 - [Crier's Scroll](https://everquest.allakhazam.com/db/item.html?item=6184)
* 18457 - [Crusades of the High Scale](https://everquest.allakhazam.com/db/item.html?item=21313)
* 18458 - [Head Housekeeper's Log](https://everquest.allakhazam.com/db/item.html?item=21313)
* 18456 - [Historic Article](https://everquest.allakhazam.com/db/item.html?item=21314)
* 1671 - [Icon of the High Scale](https://everquest.allakhazam.com/db/item.html?item=29782) (Ground Spawn)
* 18452 - [Merchant's Letter](https://everquest.allakhazam.com/db/item.html?item=6169)
* 18459 - [Neh`Ashiir's Diary](https://everquest.allakhazam.com/db/item.html?item=29783)
* 18450 - [Personal Diary Page](https://everquest.allakhazam.com/db/item.html?item=21649)
* 18454 - [Priest's Diary Page](https://everquest.allakhazam.com/db/item.html?item=6168)
* 18455 - [Student's Log](https://everquest.allakhazam.com/db/item.html?item=27738)
* 18453 - [Written Announcement](https://everquest.allakhazam.com/db/item.html?item=6167)

My two cents: Barring explicit evidence proving it wasn't already dropping (which has proven hard to find thus far), this should probably be left in (not content flagged).  It won't affect the outcome/content flag of epics anyway and provides lore and flavor to the zone.  It is most definitely Kunark era anyway and at best would just be content flagged to Kunark_EpicsEra even if they were put in right before epic release.

One observation I have had: Written Announcement (Allas Item ID: 6167), Priest's Diary Page (Allas Item ID: 6168), Merchant's Letter (Allas Item ID: 6169), and Crier's Scroll (Allas Item ID: 6184) all have lower item ID's.  The other items in that list are above 21K values.  If I had to *speculate*, I'd say the lower item values were in at release as flavor lore, and the others were added in as epics were being worked on.  But again, this is circumstantial and not concrete - just food for thought.

**Comment by nazwadi** [comment]
> Remaining list of NPC's to review:
> 
>     * **Kilidna** is Omens of War era (Shadowknight Epic 2.0) and should be disabled.

Evidence found thus far indicating Kilidna is probalby out of era:
1. Alla's specifically labels as Omens of War era: https://everquest.allakhazam.com/db/npc.html?id=16202
2. Nov 2004 Comment stating this is for SK 2.0 Epic: https://everquest.allakhazam.com/db/npc.html?id=16202#m109943792230680
3. Earliest comment Oct 17 2004: "what quest is she for": https://everquest.allakhazam.com/db/npc.html?id=16202#m109806897747562
4. Does not appear in p99 wiki, and no matches on p99 forums
5. Kilidna's Head (the only thing in Kilidna's loot table) is tagged as Omens of War SK 2.0 (https://everquest.allakhazam.com/db/item.html?item=33050)
6. Hits between 700 - 4600, HP 100K; compare this to Lord Ghiosk at 77 - 213 per hit with 24K HP, or Lord Rak`Ashiir with 12750 HP and 60-155 dmg per hit.

**Comment by nazwadi** [comment]
>Remaining list of NPC's to review:
> * a Mighty Golem - name changed to "Mighty Golem" [on Feb 15 2017 patch](https://everquest.allakhazam.com/db/npc.html?id=13080#m148780582594256927); earliest Alla's posts are 2003

Evidence showing this mob is not classic:
* Earliest post from Alla's is Sep 12, 2003 here: https://everquest.allakhazam.com/db/npc.html?id=13080#m106339596435648
* CoM was first revamped in the [August 26, 2003 patch on EQ Live](https://github.com/Gates-Of-Time/patcheq/blob/master/patches-2003-2.txt#L497):
>- The Deep, Charasis (Howling Stones), Dragon Necropolis, Siren's 
Grotto, The Hole, The City of Mist, and The Accursed Temple of Cazic-
Thule have been partially revamped. Gameplay in these zones has been 
improved, based on feedback from players and careful review of the 
content. The changes are not dramatic, but make these zones more 
entertaining to play in. 

P99 forum discussion stating not classic:
![image](https://user-images.githubusercontent.com/8131324/208455980-c9519d60-ef1f-4b5e-b5ec-8b5b5ff157c6.png)

Source: https://www.project1999.com/forums/showthread.php?t=32838&highlight=Mighty+Golem

This forum post indicates that with this mob not being classic, the Mace of the Shadowed Soul should only drop from Lord Ghiosk.  One of the posters mentions that "a Mighty Golem" didn't appear until the zone was revamped.  The zone was first revamped in the 26 August 2003 patch on live.  This makes sense why the first comment on this mob was on 12 September 2003.

**Comment by nazwadi** [comment]
Tradeskill Validation placement complete.  There is 1x Brew Barrel at (Y) -129.14 (X) -637 (Y) 83.

I suppose that sometimes while fighting our way through a cursed trade city from the Sathir Dynasty filled with golems, spirits, and goo we get a bit parched and feel the need to stop and brew a different kind of spirit.  Cheers.

**Comment by nazwadi** [comment]
> ## Items Not Dropping (Running List)

Update - Only Ruined scale items 1291 - 1295 aren't dropping in CoM.  The others I have located and updated the post above with links to all.
10. [1291 - Ruined Scaled Sleeves ](https://editor.fvproject.com/index.php?editor=loot&action=32&search=1291)(not dropping in CoM)
12. [1292 - Ruined Scaled Bracelet](https://editor.fvproject.com/index.php?editor=loot&action=32&search=1292) (not dropping in CoM)
13. [1293 - Ruined Scaled Gloves](https://editor.fvproject.com/index.php?editor=loot&action=32&search=1293) (not dropping in CoM)
14. [1294 - Ruined Scaled Pants](https://editor.fvproject.com/index.php?editor=loot&action=32&search=1294) (not dropping in CoM)
15. [1295 - Ruined Scaled Boots](https://editor.fvproject.com/index.php?editor=loot&action=32&search=1295) (not dropping in CoM)

**Comment by nazwadi** [comment]
NPC List I listed above are no longer spawning in CoM.  Thanks TT!
https://github.com/Gates-Of-Time/development-tracker/issues/25#issuecomment-1279983785

**Comment by nazwadi** [comment]
### Neh`Ashiir Loot

#### Ornate Rune Shield
Synopsis: Ornate Rune Shield Should be in Neh`Ashiir's Lootdrop table.

> Ornate Rune Shield currently configured to drop from Terror and Dread Wraiths. Alla's seems to indicate it was moved to those mobs at some point, because there's a post on Dec 16 2000 (https://everquest.allakhazam.com/db/item.html?item=1120) showing it dropped from Neh`Ashiir. P99 (https://wiki.project1999.com/Ornate_Rune_Shield) says that as well. More to follow. I'll continue to look for additional sources.

December 16, 2000:
>Shield is uncommon drop but still about 60%. Rest of the time she drops only quest torch and a no rent key of torsis. Respawn time on neh'ashiir reaver is 2 hours so you might have to kill her twice to get one shield. Very nice shield tho =)
 
Source: https://everquest.allakhazam.com/db/item.html?item=1120#m97698603532571 (60% chance)

---

Nov 19, 2001:
>Yup, killed Neh'Ashiir a couple times so far with my guild and we always ended up with the shield. No torch or staff either.

Source: https://everquest.allakhazam.com/db/item.html?item=1120#m100615535474712 (100% chance)

---

Aug 23, 2001:
>i've killed neh`ashiir 9 times so far trying to get the torch for my epic, so far 9 shields and 0 torches have dropped. oh well, just my luck. never seen the staff though, so i can't comment on that. 

Source: https://everquest.allakhazam.com/db/item.html?item=1120#m99856068050980 (100% chance)

---

Nov 09, 2000:
>i believe common is ornate rune shield, while the rare is a great ranger staff--woodman's staff (31/35).


Source: https://everquest.allakhazam.com/db/npc.html?id=5263&p=4#m97380668632255

---

Nov 14, 2000:
>Common drop is Ornate Runed Sheild +9 INT + 15 AC + 10 Mana +5 SV all resists. Rare drop is the Torch for the Mage FA quests. It is kind of debatable whether ORS or Torch is common but in the 5 times we've killed him he has dropped Torch 3 times and ORS twice.

Source: https://everquest.allakhazam.com/db/npc.html?id=5263&p=4#m97418336713356

---

P99 Wiki shows this is a common drop from Neh`Ashiir (https://wiki.project1999.com/Neh%60Ashiir)

#### Neh`Ashiir's Diary
https://everquest.allakhazam.com/db/npc.html?id=5263 states that only the quest-respawned version of Neh`Ashiir should drop the diary.  In our db it is found in the lootdrop tables for both versions.

**Comment by nazwadi** [comment]
Ornate Rune Shield has been added to Neh`Ashiir's loot table.  It will take effect after next server reboot.

**Comment by nazwadi** [comment]
### Neh`Ashiir Spells
Synopsis: Currently set to Default Enchanter spell list; missing complete heal effect.

**Complete Heals**
Sources: 
* (Jan 18 2001) https://everquest.allakhazam.com/db/npc.html?id=5263&p=4#m97982737920118
* (Oct 29 2003) https://everquest.allakhazam.com/db/npc.html?id=5263&p=3#m10674566603256
* https://wiki.project1999.com/Neh%60Ashiir
* (March 11, 2006) https://everquest.allakhazam.com/db/npc.html?id=5263&p=2#m114205707321272
* (July 21, 2011) https://everquest.allakhazam.com/db/npc.html?id=5263#m1311229807110162260
* (July 5, 2016) https://everquest.allakhazam.com/db/npc.html?id=5263#m1469506741220609333
